//! Axum routes. Handlers validate transport/security concerns then delegate to ports.
use crate::{
    API_PREFIX,
    auth::{self, Authenticator},
    dto::{
        ArtifactDiscoverPayload, ChangeApprovalDto, ChangeBeginPayload, ChangeSessionDto,
        FileDiffDto, FileEntryDto, FileReadDto, MutationAction, MutationCommand, MutationRequest,
        OperationDto, ResourceDto, ResourceKind, SessionDto, safe_content_disposition,
    },
    error::ApiError,
    ports::{
        ConsoleAuditEvent, ConsoleDirection, ConsoleFrame, ConsoleSession, ManagementApi,
        MutationContext, OperationEvent, Permission, VerifiedActor,
    },
    security::{
        DangerRateLimiter, SecurityConfig, check_origin, check_state_change, validate_content_type,
        validate_relative_path,
    },
};
use axum::extract::ws::{Message, WebSocket};
use axum::{
    Json, Router,
    body::Body,
    body::Bytes,
    extract::{
        Extension, OriginalUri, Path, Query, State, WebSocketUpgrade,
        rejection::{JsonRejection, QueryRejection},
    },
    http::{HeaderMap, HeaderValue, Request, StatusCode, header},
    middleware::{self, Next},
    response::{
        IntoResponse, Response,
        sse::{Event, KeepAlive, Sse},
    },
};
use futures_core::Stream;
use serde::Deserialize;
use serde_json::{Value, json};
use std::{
    convert::Infallible,
    sync::Arc,
    time::{Duration, SystemTime, UNIX_EPOCH},
};
use tokio::time::{self, Instant};
use uuid::Uuid;

const CONSOLE_FRAME_LIMIT: usize = 64 * 1024;
const CONSOLE_IDLE: Duration = Duration::from_secs(15 * 60);
const CONSOLE_LIFETIME: Duration = Duration::from_secs(2 * 60 * 60);
const CONSOLE_IO_TIMEOUT: Duration = Duration::from_secs(30);
const CONSOLE_CLOSE_TIMEOUT: Duration = Duration::from_secs(5);
const SSE_IDLE: Duration = Duration::from_secs(5 * 60);
const SSE_LIFETIME: Duration = Duration::from_secs(2 * 60 * 60);

/// Correlation identifier generated by the API and passed to application audit ports.
#[derive(Clone, Debug)]
pub struct RequestId(pub String);

struct MutationDispatch<'a> {
    state: ApiState,
    actor: VerifiedActor,
    request_id: RequestId,
    resource: &'a str,
    id: Option<&'a str>,
    command: MutationCommand,
    action: MutationAction,
    headers: HeaderMap,
    body: Result<Json<MutationRequest>, JsonRejection>,
}

/// Shared route dependencies.
#[derive(Clone)]
pub struct ApiState {
    pub management: Arc<dyn ManagementApi>,
    pub authenticator: Arc<Authenticator>,
    pub security: Arc<SecurityConfig>,
    pub limiter: Arc<DangerRateLimiter>,
}
impl ApiState {
    pub fn new(
        management: Arc<dyn ManagementApi>,
        authenticator: Arc<Authenticator>,
        security: Arc<SecurityConfig>,
    ) -> Result<Self, ApiError> {
        security.validate()?;
        Ok(Self {
            management,
            authenticator,
            security,
            limiter: Arc::new(DangerRateLimiter::default()),
        })
    }
}

/// Build the public health endpoints and authenticated management API.
pub fn router(
    management: Arc<dyn ManagementApi>,
    authenticator: Arc<Authenticator>,
    security: Arc<SecurityConfig>,
) -> Result<Router, ApiError> {
    let state = ApiState::new(management, authenticator.clone(), security)?;
    let mut protected = Router::new();
    for resource in ResourceKind::ALL {
        let collection = format!("{API_PREFIX}/{}", resource.as_str());
        let item = format!("{collection}/{{id}}");
        if resource == ResourceKind::SftpEndpoints {
            protected = protected.route(&collection, axum::routing::get(list_sftp_endpoints));
            protected = protected.route(&item, axum::routing::get(get_sftp_endpoint));
            continue;
        }
        protected = protected.route(&collection, axum::routing::get(list));
        protected = protected.route(&item, axum::routing::get(get));
    }
    protected = protected
        .route(
            "/api/v1/change-sessions",
            axum::routing::post(begin_change_session),
        )
        .route(
            "/api/v1/change-sessions/{id}/plan",
            axum::routing::post(plan_change),
        )
        .route(
            "/api/v1/change-sessions/{id}/approve",
            axum::routing::post(approve_change),
        )
        .route(
            "/api/v1/change-sessions/{id}/apply",
            axum::routing::post(explicit_mutate),
        )
        .route(
            "/api/v1/change-sessions/{id}/verify",
            axum::routing::post(explicit_mutate),
        )
        .route(
            "/api/v1/change-sessions/{id}/accept",
            axum::routing::post(explicit_mutate),
        )
        .route(
            "/api/v1/change-sessions/{id}/rollback",
            axum::routing::post(explicit_mutate),
        )
        .route(
            "/api/v1/artifacts/discover",
            axum::routing::post(discover_artifacts),
        )
        .route(
            "/api/v1/sftp-endpoints/{id}/scan",
            axum::routing::post(scan_sftp),
        )
        .route(
            "/api/v1/operations/{id}/events",
            axum::routing::get(operation_events),
        )
        .route(
            "/api/v1/execution-units/{id}/console",
            axum::routing::get(console),
        )
        .route("/api/v1/session", axum::routing::post(session))
        .route(
            "/api/v1/health/providers",
            axum::routing::get(provider_health),
        );
    let file_routes = Router::new()
        .route(
            "/api/v1/execution-units/{id}/files",
            axum::routing::get(file_browse),
        )
        .route(
            "/api/v1/execution-units/{id}/files/browse",
            axum::routing::get(file_browse),
        )
        .route(
            "/api/v1/execution-units/{id}/files/read",
            axum::routing::get(file_read),
        )
        .route(
            "/api/v1/execution-units/{id}/files/download",
            axum::routing::get(file_download),
        )
        .route(
            "/api/v1/execution-units/{id}/files/diff",
            axum::routing::get(file_diff),
        )
        .layer(axum::extract::DefaultBodyLimit::max(
            state.security.body_limit,
        ));
    let staged_content_route = Router::new()
        .route(
            "/api/v1/change-sessions/{id}/staged-content",
            axum::routing::post(stage_content),
        )
        .layer(axum::extract::DefaultBodyLimit::max(
            state.security.upload_limit,
        ));
    let protected = protected
        .layer(axum::extract::DefaultBodyLimit::max(
            state.security.body_limit,
        ))
        .merge(file_routes)
        .merge(staged_content_route)
        .with_state(state.clone())
        .layer(middleware::from_fn_with_state(
            authenticator,
            auth::middleware,
        ));
    let public = Router::new()
        .route("/health", axum::routing::get(health))
        .route("/live", axum::routing::get(live))
        .route("/ready", axum::routing::get(ready))
        .route("/metrics", axum::routing::get(metrics))
        .with_state(state);
    Ok(public
        .merge(protected)
        .fallback(api_not_found)
        .layer(middleware::from_fn(request_id))
        .layer(middleware::from_fn(security_headers)))
}

async fn list(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    OriginalUri(uri): OriginalUri,
) -> Result<Json<Vec<ResourceDto>>, ApiError> {
    let resource = resource_from_path(uri.path())?;
    state
        .management
        .authorize(&actor, resource.as_str(), None, read_permission(resource))
        .await?;
    Ok(Json(
        state.management.list(resource.as_str(), &actor).await?,
    ))
}

async fn session(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    headers: HeaderMap,
) -> Result<Response, ApiError> {
    if actor.kind != crate::ports::ActorKind::Browser {
        return Err(ApiError::Forbidden);
    }
    check_origin(&state.security, &headers)?;
    state
        .limiter
        .check(
            &actor,
            state.security.dangerous_rate_limit,
            state.security.dangerous_rate_window,
        )
        .await?;
    let mut response = Json(SessionDto {
        csrf_token: state.security.csrf.issue(&actor)?,
    })
    .into_response();
    response
        .headers_mut()
        .insert(header::CACHE_CONTROL, HeaderValue::from_static("no-store"));
    Ok(response)
}

async fn begin_change_session(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Extension(request_id): Extension<RequestId>,
    headers: HeaderMap,
    body: Result<Json<ChangeBeginPayload>, JsonRejection>,
) -> Result<Json<ChangeSessionDto>, ApiError> {
    require_json(&headers, state.security.body_limit)?;
    check_state_change(&state.security, &headers, &actor).await?;
    let idempotency_key = required_header(&headers, "idempotency-key", 128)?;
    let payload = parse_json_body(body)?;
    validate_uuid_path(&payload.service_id, "service_id")?;
    validate_uuid_path(&payload.cluster_id, "cluster_id")?;
    state
        .management
        .begin_change_session(&actor, payload, idempotency_key, &request_id.0)
        .await
        .map(Json)
}
async fn get(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    OriginalUri(uri): OriginalUri,
    Path(id): Path<String>,
) -> Result<Json<ResourceDto>, ApiError> {
    let resource = resource_from_path(uri.path())?;
    state
        .management
        .authorize(
            &actor,
            resource.as_str(),
            Some(&id),
            read_permission(resource),
        )
        .await?;
    Ok(Json(
        state.management.get(resource.as_str(), &id, &actor).await?,
    ))
}

fn resource_from_path(path: &str) -> Result<ResourceKind, ApiError> {
    let resource = path
        .split('/')
        .filter(|segment| !segment.is_empty())
        .nth(2)
        .ok_or(ApiError::NotFound)?;
    ResourceKind::parse(resource)
}

async fn list_sftp_endpoints(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
) -> Result<Json<Vec<crate::dto::SftpEndpointDto>>, ApiError> {
    state
        .management
        .authorize(&actor, "sftp-endpoints", None, Permission::EndpointRead)
        .await?;
    state.management.list_sftp_endpoints(&actor).await.map(Json)
}

async fn get_sftp_endpoint(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Path(id): Path<String>,
) -> Result<Json<crate::dto::SftpEndpointDto>, ApiError> {
    validate_uuid_path(&id, "endpoint_id")?;
    state
        .management
        .authorize(
            &actor,
            "sftp-endpoints",
            Some(&id),
            Permission::EndpointRead,
        )
        .await?;
    state
        .management
        .get_sftp_endpoint(&actor, &id)
        .await
        .map(Json)
}

/// Action routes use the mutation envelope, but bind a closed operation name
/// to a concrete resource and object path.
async fn explicit_mutate(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Extension(request_id): Extension<RequestId>,
    OriginalUri(uri): OriginalUri,
    Path(id): Path<String>,
    headers: HeaderMap,
    body: Result<Json<MutationRequest>, JsonRejection>,
) -> Result<Json<OperationDto>, ApiError> {
    validate_uuid_path(&id, "change_session_id")?;
    let action_name = uri_action_name(uri.path());
    let command = match action_name {
        "apply" => MutationCommand::Apply,
        "verify" => MutationCommand::Verify,
        "accept" => MutationCommand::Accept,
        "rollback" => MutationCommand::Rollback,
        _ => return Err(ApiError::NotFound),
    };
    dispatch_mutation(MutationDispatch {
        state,
        actor,
        request_id,
        resource: "change-sessions",
        id: Some(&id),
        command,
        action: MutationAction::Change,
        headers,
        body,
    })
    .await
}

fn uri_action_name(path: &str) -> &str {
    path.rsplit('/')
        .find(|segment| !segment.is_empty())
        .unwrap_or("")
}

async fn plan_change(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Extension(request_id): Extension<RequestId>,
    Path(id): Path<String>,
    headers: HeaderMap,
    body: Result<Json<MutationRequest>, JsonRejection>,
) -> Result<Json<crate::dto::ChangePlanResultDto>, ApiError> {
    validate_uuid_path(&id, "change_session_id")?;
    let resource = "change-sessions";
    require_json(&headers, state.security.body_limit)?;
    let request = parse_json_body(body)?;
    request.validate_for(resource, MutationCommand::Plan, MutationAction::Change)?;
    validate_request_hash_header(&headers, &request.request_hash)?;
    check_state_change(&state.security, &headers, &actor).await?;
    state
        .management
        .authorize(&actor, resource, Some(&id), Permission::ChangePlan)
        .await?;
    let idem = required_header(&headers, "idempotency-key", 128)?;
    let if_match = required_header(&headers, "if-match", 256)?;
    let now = unix_now();
    if request.expires_at <= now || request.expires_at > now.saturating_add(24 * 60 * 60) {
        return Err(ApiError::InvalidRequest(
            "plan expiry is outside the allowed window",
        ));
    }
    state
        .management
        .plan_change(
            &actor,
            resource,
            &id,
            request.clone(),
            MutationContext {
                actor: actor.clone(),
                idempotency_key: idem.to_owned(),
                if_match: if_match.to_owned(),
                session_version: Some(parse_session_version(if_match)?),
                request_hash: request.request_hash,
                expires_at: request.expires_at,
                request_id: request_id.0,
            },
        )
        .await
        .map(Json)
}

async fn approve_change(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Extension(request_id): Extension<RequestId>,
    Path(id): Path<String>,
    headers: HeaderMap,
    body: Result<Json<MutationRequest>, JsonRejection>,
) -> Result<Json<ChangeApprovalDto>, ApiError> {
    validate_uuid_path(&id, "change_session_id")?;
    let resource = "change-sessions";
    require_json(&headers, state.security.body_limit)?;
    let request = parse_json_body(body)?;
    request.validate_for(resource, MutationCommand::Approve, MutationAction::Change)?;
    validate_request_hash_header(&headers, &request.request_hash)?;
    check_state_change(&state.security, &headers, &actor).await?;
    state
        .management
        .authorize(&actor, resource, Some(&id), Permission::ChangeApprove)
        .await?;
    let idem = required_header(&headers, "idempotency-key", 128)?;
    let if_match = required_header(&headers, "if-match", 256)?;
    let now = unix_now();
    if request.expires_at <= now || request.expires_at > now.saturating_add(24 * 60 * 60) {
        return Err(ApiError::InvalidRequest(
            "plan expiry is outside the allowed window",
        ));
    }
    state
        .management
        .approve_change(
            &actor,
            resource,
            &id,
            request.clone(),
            MutationContext {
                actor: actor.clone(),
                idempotency_key: idem.to_owned(),
                if_match: if_match.to_owned(),
                session_version: None,
                request_hash: request.request_hash,
                expires_at: request.expires_at,
                request_id: request_id.0,
            },
        )
        .await
        .map(Json)
}

/// Store bytes in the active, actor-owned change session. The response is a
/// content reference only; plan payloads never carry file bytes.
async fn stage_content(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Path(id): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Result<Json<crate::dto::StagedContentDto>, ApiError> {
    validate_uuid_path(&id, "change_session_id")?;
    if headers.get_all(header::CONTENT_TYPE).iter().count() != 1
        || headers
            .get(header::CONTENT_TYPE)
            .and_then(|value| value.to_str().ok())
            .and_then(|value| value.split(';').next())
            .map(str::trim)
            != Some("application/octet-stream")
    {
        return Err(ApiError::InvalidRequest(
            "application/octet-stream content type is required",
        ));
    }
    if headers.get_all(header::CONTENT_LENGTH).iter().count() > 1 {
        return Err(ApiError::InvalidRequest("invalid content length"));
    }
    if let Some(length) = headers.get(header::CONTENT_LENGTH) {
        let length = length
            .to_str()
            .ok()
            .and_then(|value| value.parse::<u64>().ok())
            .ok_or(ApiError::InvalidRequest("invalid content length"))?;
        if length > state.security.upload_limit as u64 {
            return Err(ApiError::PayloadTooLarge);
        }
        if length != body.len() as u64 {
            return Err(ApiError::InvalidRequest(
                "content length does not match body",
            ));
        }
    }
    if body.len() > state.security.upload_limit {
        return Err(ApiError::PayloadTooLarge);
    }
    check_state_change(&state.security, &headers, &actor).await?;
    state
        .management
        .authorize(&actor, "change-sessions", Some(&id), Permission::ChangePlan)
        .await?;
    let if_match = required_header(&headers, "if-match", 256)?;
    let session_version = parse_session_version(if_match)?;
    let idempotency_key = required_header(&headers, "idempotency-key", 128)?;
    let classification =
        parse_staged_classification(required_header(&headers, "x-kitsunebi-classification", 64)?)?;
    let request_hash = crate::plan_hash(&body);
    state
        .management
        .stage_content(
            &actor,
            crate::ports::StageContentRequest {
                session_id: id,
                bytes: body.to_vec(),
                classification,
                session_version,
                idempotency_key: idempotency_key.to_owned(),
                request_hash,
            },
        )
        .await
        .map(Json)
}

/// Record a bounded out-of-band SFTP observation. This is an observation
/// attached to an active change session, not a realtime audit stream and not
/// a provider mutation.
async fn scan_sftp(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Extension(request_id): Extension<RequestId>,
    Path(endpoint_id): Path<String>,
    headers: HeaderMap,
    body: Result<Json<crate::dto::SftpScanPayload>, JsonRejection>,
) -> Result<Json<crate::dto::SftpScanDto>, ApiError> {
    validate_uuid_path(&endpoint_id, "endpoint_id")?;
    require_json(&headers, state.security.body_limit)?;
    let payload = parse_json_body(body)?;
    payload.validate()?;
    check_state_change(&state.security, &headers, &actor).await?;
    let permission = Permission::ChangePlan;
    state
        .management
        .authorize(&actor, "sftp-endpoints", Some(&endpoint_id), permission)
        .await?;
    let idempotency_key = required_header(&headers, "idempotency-key", 128)?;
    let if_match = required_header(&headers, "if-match", 256)?;
    if payload.endpoint_id != endpoint_id {
        return Err(ApiError::InvalidRequest("endpoint_id does not match route"));
    }
    let payload_hash = serde_json::to_vec(&payload)
        .map(|bytes| crate::plan_hash(&bytes))
        .map_err(|_| ApiError::InvalidRequest("sftp scan payload"))?;
    state
        .management
        .scan_sftp(
            &actor,
            &endpoint_id,
            payload,
            MutationContext {
                actor: actor.clone(),
                idempotency_key: idempotency_key.to_owned(),
                if_match: if_match.to_owned(),
                session_version: None,
                request_hash: payload_hash,
                expires_at: unix_now().saturating_add(24 * 60 * 60),
                request_id: request_id.0,
            },
        )
        .await
        .map(Json)
}

async fn discover_artifacts(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    headers: HeaderMap,
    body: Result<Json<ArtifactDiscoverPayload>, JsonRejection>,
) -> Result<Json<Vec<crate::dto::ArtifactCandidateDto>>, ApiError> {
    require_json(&headers, state.security.body_limit)?;
    let payload = parse_json_body(body)?;
    payload.validate()?;
    if actor.kind == crate::ports::ActorKind::Browser {
        check_origin(&state.security, &headers)?;
    }
    state
        .management
        .authorize(&actor, "artifacts", None, Permission::ArtifactDiscover)
        .await?;
    state
        .limiter
        .check(
            &actor,
            state.security.dangerous_rate_limit,
            state.security.dangerous_rate_window,
        )
        .await?;
    state
        .management
        .discover_artifacts(&actor, payload)
        .await
        .map(Json)
}

async fn dispatch_mutation(dispatch: MutationDispatch<'_>) -> Result<Json<OperationDto>, ApiError> {
    let MutationDispatch {
        state,
        actor,
        request_id,
        resource,
        id,
        command,
        action,
        headers,
        body,
    } = dispatch;
    let body_limit = state.security.body_limit;
    require_json(&headers, body_limit)?;
    let request = parse_json_body(body)?;
    request.validate_for(resource, command, action)?;
    validate_request_hash_header(&headers, &request.request_hash)?;
    check_state_change(&state.security, &headers, &actor).await?;
    let permission = permission_for(resource, action, command);
    state
        .management
        .authorize(&actor, resource, id, permission)
        .await?;
    if dangerous_mutation(action, command) {
        state
            .limiter
            .check(
                &actor,
                state.security.dangerous_rate_limit,
                state.security.dangerous_rate_window,
            )
            .await?;
    }
    let idem = required_header(&headers, "idempotency-key", 128)?;
    let if_match = required_header(&headers, "if-match", 256)?;
    let now = unix_now();
    if request.expires_at <= now || request.expires_at > now.saturating_add(24 * 60 * 60) {
        return Err(ApiError::InvalidRequest(
            "plan expiry is outside the allowed window",
        ));
    }
    let operation = state
        .management
        .mutate(
            resource,
            id,
            request.clone(),
            MutationContext {
                actor,
                idempotency_key: idem.to_owned(),
                if_match: if_match.to_owned(),
                session_version: None,
                request_hash: request.request_hash,
                expires_at: request.expires_at,
                request_id: request_id.0,
            },
        )
        .await?;
    Ok(Json(operation))
}

fn read_permission(resource: ResourceKind) -> Permission {
    match resource {
        ResourceKind::Artifacts => Permission::ArtifactDiscover,
        ResourceKind::Worlds => Permission::WorldRead,
        ResourceKind::Endpoints => Permission::EndpointRead,
        ResourceKind::AccessPolicies => Permission::AccessRead,
        ResourceKind::AuditEvents => Permission::AuditRead,
        ResourceKind::Operations => Permission::OperationRead,
        _ => Permission::ServiceRead,
    }
}

fn permission_for(resource: &str, action: MutationAction, command: MutationCommand) -> Permission {
    match action {
        MutationAction::Change => match resource {
            "worlds" => Permission::WorldWrite,
            "endpoints" => Permission::EndpointWrite,
            "access-policies" => Permission::AccessManage,
            _ => match command {
                MutationCommand::Plan => Permission::ChangePlan,
                MutationCommand::Approve => Permission::ChangeApprove,
                MutationCommand::Apply => Permission::ChangeApply,
                MutationCommand::Verify => Permission::ChangeVerify,
                MutationCommand::Accept => Permission::ChangeAccept,
                MutationCommand::Rollback => Permission::ChangeRollback,
            },
        },
    }
}
fn dangerous_mutation(action: MutationAction, command: MutationCommand) -> bool {
    !matches!(
        (action, command),
        (MutationAction::Change, MutationCommand::Plan)
            | (MutationAction::Change, MutationCommand::Verify)
    )
}

async fn operation_events(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Path(id): Path<String>,
) -> Result<Sse<impl Stream<Item = Result<Event, Infallible>>>, ApiError> {
    state
        .management
        .authorize(&actor, "operations", Some(&id), Permission::OperationRead)
        .await?;
    let mut stream = state.management.open_operation_stream(&actor, &id).await?;
    let deadline = Instant::now() + SSE_LIFETIME;
    let output = async_stream::stream! {
        loop {
            tokio::select! {
                _ = time::sleep_until(deadline) => break,
                event = time::timeout(SSE_IDLE, stream.next()) => {
                    match event {
                        Ok(Ok(Some(event))) => yield Ok(event_to_sse(event)),
                        Ok(Ok(None)) | Ok(Err(_)) | Err(_) => break,
                    }
                }
            }
        }
    };
    Ok(Sse::new(output).keep_alive(KeepAlive::default()))
}
fn event_to_sse(event: OperationEvent) -> Event {
    Event::default()
        .event("operation")
        .json_data(event)
        .unwrap_or_else(|_| Event::default().event("operation"))
}

async fn console(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Path(id): Path<String>,
    headers: HeaderMap,
    upgrade: WebSocketUpgrade,
) -> Result<Response, ApiError> {
    state
        .management
        .authorize(
            &actor,
            "execution-units",
            Some(&id),
            Permission::ConsoleRead,
        )
        .await?;
    let can_command = match state
        .management
        .authorize(
            &actor,
            "execution-units",
            Some(&id),
            Permission::ConsoleSend,
        )
        .await
    {
        Ok(_) => true,
        // A read-only console is a supported session. Other authorization
        // failures (for example a storage outage) must not be hidden as a
        // missing command grant.
        Err(ApiError::Forbidden | ApiError::NotFound) => false,
        Err(error) => return Err(error),
    };
    if actor.kind == crate::ports::ActorKind::Browser {
        check_origin(&state.security, &headers)?;
        if headers.contains_key("x-csrf-token") {
            return Err(ApiError::Forbidden);
        }
    }
    if can_command {
        if actor.kind == crate::ports::ActorKind::Browser {
            verify_console_protocol(&headers, &state.security, &actor)?;
        } else {
            // Service actors use the explicit originless path.
            check_state_change(&state.security, &headers, &actor).await?;
        }
    } else if !has_console_base_protocol(&headers)? {
        return Err(ApiError::Forbidden);
    }
    let session = state.management.open_console(&actor, &id).await?;
    let limiter = state.limiter.clone();
    let actor_for_relay = actor.clone();
    let rate_limit = state.security.dangerous_rate_limit;
    let rate_window = state.security.dangerous_rate_window;
    Ok(upgrade
        .protocols(["kitsunebi.v1"])
        .max_write_buffer_size(CONSOLE_FRAME_LIMIT * 2)
        .max_message_size(CONSOLE_FRAME_LIMIT)
        .max_frame_size(CONSOLE_FRAME_LIMIT)
        .on_upgrade(move |socket| {
            console_relay(
                socket,
                session,
                can_command,
                limiter,
                actor_for_relay,
                rate_limit,
                rate_window,
            )
        }))
}

fn has_console_base_protocol(headers: &HeaderMap) -> Result<bool, ApiError> {
    let mut has_base = false;
    let mut has_csrf = false;
    for value in headers.get_all("sec-websocket-protocol") {
        let value = value.to_str().map_err(|_| ApiError::Forbidden)?;
        for protocol in value.split(',') {
            let protocol = protocol.trim();
            if protocol == "kitsunebi.v1" {
                if has_base {
                    return Err(ApiError::Forbidden);
                }
                has_base = true;
            } else if protocol.strip_prefix("csrf.").is_some() {
                if has_csrf {
                    return Err(ApiError::Forbidden);
                }
                has_csrf = true;
            } else {
                return Err(ApiError::Forbidden);
            }
        }
    }
    Ok(has_base)
}

fn verify_console_protocol(
    headers: &HeaderMap,
    security: &SecurityConfig,
    actor: &VerifiedActor,
) -> Result<(), ApiError> {
    let mut has_base = false;
    let mut csrf = None;
    for value in headers.get_all("sec-websocket-protocol") {
        let value = value.to_str().map_err(|_| ApiError::Forbidden)?;
        for protocol in value.split(',').map(str::trim) {
            if protocol.is_empty() {
                return Err(ApiError::Forbidden);
            }
            if protocol == "kitsunebi.v1" {
                if has_base {
                    return Err(ApiError::Forbidden);
                }
                has_base = true;
            } else if let Some(token) = protocol.strip_prefix("csrf.") {
                if csrf.replace(token).is_some() {
                    return Err(ApiError::Forbidden);
                }
            } else {
                return Err(ApiError::Forbidden);
            }
        }
    }
    let token = csrf.ok_or(ApiError::Forbidden)?;
    if !has_base || !security.csrf.verify(actor, token) {
        return Err(ApiError::Forbidden);
    }
    Ok(())
}
async fn console_relay(
    mut socket: WebSocket,
    mut session: Box<dyn ConsoleSession>,
    can_command: bool,
    limiter: Arc<DangerRateLimiter>,
    actor: VerifiedActor,
    rate_limit: usize,
    rate_window: Duration,
) {
    let end = Instant::now() + CONSOLE_LIFETIME;
    loop {
        tokio::select! {
            _ = time::sleep_until(end) => break,
            inbound = time::timeout(CONSOLE_IDLE, socket.recv()) => {
                let message = match inbound {
                    Ok(Some(Ok(message))) => message,
                    _ => break,
                };
                let frame = match message {
                    Message::Text(text) => {
                        if !can_command || text.len() > CONSOLE_FRAME_LIMIT {
                            break;
                        }
                        if limiter.check(&actor, rate_limit, rate_window).await.is_err() {
                            break;
                        }
                        ConsoleFrame::Text(text.to_string())
                    }
                    Message::Binary(bytes) => {
                        if !can_command || bytes.len() > CONSOLE_FRAME_LIMIT {
                            break;
                        }
                        if limiter.check(&actor, rate_limit, rate_window).await.is_err() {
                            break;
                        }
                        ConsoleFrame::Binary(bytes.to_vec())
                    }
                    Message::Ping(_) | Message::Pong(_) => continue,
                    Message::Close(_) => break,
                };
                if session
                    .record(audit_event(&frame, ConsoleDirection::ClientToBackend))
                    .await
                    .is_err()
                {
                    break;
                }
                if !matches!(
                    time::timeout(CONSOLE_IO_TIMEOUT, session.send(frame)).await,
                    Ok(Ok(()))
                ) {
                    break;
                }
            }
            backend = time::timeout(CONSOLE_IDLE, session.receive()) => {
                match backend {
                    Ok(Ok(Some(ConsoleFrame::Text(text)))) => {
                        let event = ConsoleAuditEvent {
                            direction: ConsoleDirection::BackendToClient,
                            size: text.len(),
                            digest: crate::plan_hash(text.as_bytes()),
                        };
                        if session.record(event).await.is_err() {
                            break;
                        }
                        if text.len() > CONSOLE_FRAME_LIMIT
                            || !matches!(
                                time::timeout(
                                    CONSOLE_IO_TIMEOUT,
                                    socket.send(Message::Text(text.into()))
                                )
                                .await,
                                Ok(Ok(()))
                            )
                        {
                            break;
                        }
                    }
                    Ok(Ok(Some(ConsoleFrame::Binary(bytes)))) => {
                        let event = ConsoleAuditEvent {
                            direction: ConsoleDirection::BackendToClient,
                            size: bytes.len(),
                            digest: crate::plan_hash(&bytes),
                        };
                        if session.record(event).await.is_err() {
                            break;
                        }
                        if bytes.len() > CONSOLE_FRAME_LIMIT
                            || !matches!(
                                time::timeout(
                                    CONSOLE_IO_TIMEOUT,
                                    socket.send(Message::Binary(bytes.into()))
                                )
                                .await,
                                Ok(Ok(()))
                            )
                        {
                            break;
                        }
                    }
                    Ok(Ok(None)) | Ok(Err(_)) | Err(_) => break,
                }
            }
        }
    }
    let _ = time::timeout(CONSOLE_CLOSE_TIMEOUT, socket.send(Message::Close(None))).await;
    let _ = time::timeout(CONSOLE_CLOSE_TIMEOUT, session.close()).await;
}
fn audit_event(frame: &ConsoleFrame, direction: ConsoleDirection) -> ConsoleAuditEvent {
    match frame {
        ConsoleFrame::Text(text) => ConsoleAuditEvent {
            direction,
            size: text.len(),
            digest: crate::plan_hash(text.as_bytes()),
        },
        ConsoleFrame::Binary(bytes) => ConsoleAuditEvent {
            direction,
            size: bytes.len(),
            digest: crate::plan_hash(bytes),
        },
    }
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct FilePathQuery {
    path: Option<String>,
}
fn parse_file_query(
    query: Result<Query<FilePathQuery>, QueryRejection>,
) -> Result<FilePathQuery, ApiError> {
    query
        .map(|Query(query)| query)
        .map_err(|_| ApiError::InvalidRequest("invalid file query"))
}
fn query_path(query: &FilePathQuery) -> Result<String, ApiError> {
    match query.path.as_deref() {
        None | Some("") => Ok(".".to_owned()),
        Some(".") => Ok(".".to_owned()),
        Some(path) => validate_relative_path(path),
    }
}
fn validate_uuid_path(value: &str, field: &'static str) -> Result<(), ApiError> {
    if Uuid::parse_str(value).is_err() {
        return Err(ApiError::InvalidRequest(field));
    }
    Ok(())
}
async fn file_browse(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Path(id): Path<String>,
    query: Result<Query<FilePathQuery>, QueryRejection>,
) -> Result<Json<Vec<FileEntryDto>>, ApiError> {
    state
        .management
        .authorize(&actor, "execution-units", Some(&id), Permission::FilesRead)
        .await?;
    let path = query_path(&parse_file_query(query)?)?;
    Ok(Json(
        state.management.files().browse(&actor, &id, &path).await?,
    ))
}
async fn file_read(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Path(id): Path<String>,
    query: Result<Query<FilePathQuery>, QueryRejection>,
) -> Result<Json<FileReadDto>, ApiError> {
    state
        .management
        .authorize(&actor, "execution-units", Some(&id), Permission::FilesRead)
        .await?;
    let query = parse_file_query(query)?;
    let path = validate_relative_path(
        query
            .path
            .as_deref()
            .ok_or(ApiError::InvalidRequest("path is required"))?,
    )?;
    let file = state.management.files().read(&actor, &id, &path).await?;
    if file.content.len() > state.security.upload_limit {
        return Err(ApiError::PayloadTooLarge);
    }
    validate_content_type(&file.content_type)?;
    Ok(Json(file))
}
async fn file_download(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Path(id): Path<String>,
    query: Result<Query<FilePathQuery>, QueryRejection>,
) -> Result<Response, ApiError> {
    state
        .management
        .authorize(&actor, "execution-units", Some(&id), Permission::FilesRead)
        .await?;
    let query = parse_file_query(query)?;
    let path = validate_relative_path(
        query
            .path
            .as_deref()
            .ok_or(ApiError::InvalidRequest("path is required"))?,
    )?;
    let file = state
        .management
        .files()
        .download(&actor, &id, &path)
        .await?;
    download_response(file, state.security.upload_limit)
}
async fn file_diff(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
    Path(id): Path<String>,
    query: Result<Query<FilePathQuery>, QueryRejection>,
) -> Result<Json<FileDiffDto>, ApiError> {
    state
        .management
        .authorize(&actor, "execution-units", Some(&id), Permission::FilesRead)
        .await?;
    let query = parse_file_query(query)?;
    let path = validate_relative_path(
        query
            .path
            .as_deref()
            .ok_or(ApiError::InvalidRequest("path is required"))?,
    )?;
    Ok(Json(
        state.management.files().diff(&actor, &id, &path).await?,
    ))
}
fn download_response(file: FileReadDto, limit: usize) -> Result<Response, ApiError> {
    if file.content.len() > limit {
        return Err(ApiError::PayloadTooLarge);
    }
    let disposition = safe_content_disposition(&file.path)?;
    let content_type = HeaderValue::from_str(validate_content_type(&file.content_type)?)
        .map_err(|_| ApiError::InvalidRequest("invalid content type"))?;
    let mut response = Response::new(Body::from(file.content));
    response
        .headers_mut()
        .insert(header::CONTENT_TYPE, content_type);
    response.headers_mut().insert(
        header::CONTENT_DISPOSITION,
        HeaderValue::from_str(&disposition)
            .map_err(|_| ApiError::InvalidRequest("unsafe filename"))?,
    );
    Ok(response)
}

async fn health(State(state): State<ApiState>) -> Result<Json<Value>, ApiError> {
    Ok(Json(state.management.health().await?))
}
async fn provider_health(
    State(state): State<ApiState>,
    Extension(actor): Extension<VerifiedActor>,
) -> Result<Json<Value>, ApiError> {
    Ok(Json(state.management.provider_health(&actor).await?))
}
async fn live() -> Json<Value> {
    Json(json!({"status": "live"}))
}
async fn ready(State(state): State<ApiState>) -> Result<Json<Value>, ApiError> {
    Ok(Json(state.management.ready().await?))
}
async fn metrics() -> (HeaderMap, &'static str) {
    let mut h = HeaderMap::new();
    h.insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("text/plain; version=0.0.4"),
    );
    (
        h,
        "# HELP kitsunebi_api_up API availability\n# TYPE kitsunebi_api_up gauge\nkitsunebi_api_up 1\n",
    )
}

/// Keep unknown API paths machine-readable without taking ownership of the
/// controller's frontend fallback for non-API paths.
async fn api_not_found() -> ApiError {
    ApiError::NotFound
}

async fn request_id(mut request: Request<Body>, next: Next) -> Response {
    let id = Uuid::new_v4().to_string();
    request.extensions_mut().insert(RequestId(id.clone()));
    let mut response = next.run(request).await;
    if let Ok(value) = HeaderValue::from_str(&id) {
        response.headers_mut().insert("x-request-id", value);
    }
    response
}
async fn security_headers(request: Request<Body>, next: Next) -> Response {
    let mut response = next.run(request).await;
    let headers = response.headers_mut();
    headers.insert(
        "x-content-type-options",
        HeaderValue::from_static("nosniff"),
    );
    headers.insert("x-frame-options", HeaderValue::from_static("DENY"));
    headers.insert(
        "strict-transport-security",
        HeaderValue::from_static("max-age=31536000; includeSubDomains"),
    );
    headers.insert(
        "cross-origin-opener-policy",
        HeaderValue::from_static("same-origin"),
    );
    headers.insert(
        "cross-origin-resource-policy",
        HeaderValue::from_static("same-origin"),
    );
    headers.insert("referrer-policy", HeaderValue::from_static("no-referrer"));
    headers.insert("cache-control", HeaderValue::from_static("no-store"));
    headers.insert(
        "permissions-policy",
        HeaderValue::from_static("camera=(), geolocation=(), microphone=()"),
    );
    headers.insert(
        "content-security-policy",
        HeaderValue::from_static(
            "default-src 'self'; base-uri 'self'; frame-ancestors 'none'; \
             object-src 'none'; script-src 'self'; style-src 'self'",
        ),
    );
    response
}
fn require_json(headers: &HeaderMap, max_body_size: usize) -> Result<(), ApiError> {
    if headers.get_all(header::CONTENT_TYPE).iter().count() != 1 {
        return Err(ApiError::InvalidRequest(
            "application/json content type is required",
        ));
    }
    let value = headers
        .get(header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        .ok_or(ApiError::InvalidRequest(
            "application/json content type is required",
        ))?;
    if value.split(';').next().map(str::trim) != Some("application/json") {
        Err(ApiError::InvalidRequest(
            "application/json content type is required",
        ))
    } else {
        if headers.get_all(header::CONTENT_LENGTH).iter().count() > 1 {
            return Err(ApiError::InvalidRequest("invalid content length"));
        }
        let length = headers
            .get(header::CONTENT_LENGTH)
            .map(|value| {
                value
                    .to_str()
                    .ok()
                    .and_then(|value| value.parse::<u64>().ok())
                    .ok_or(ApiError::InvalidRequest("invalid content length"))
            })
            .transpose()?;
        if length.is_some_and(|length| length > max_body_size as u64) {
            Err(ApiError::PayloadTooLarge)
        } else {
            Ok(())
        }
    }
}

fn parse_json_body<T>(body: Result<Json<T>, JsonRejection>) -> Result<T, ApiError> {
    body.map(|Json(value)| value).map_err(|rejection| {
        if rejection.status() == StatusCode::PAYLOAD_TOO_LARGE {
            ApiError::PayloadTooLarge
        } else if rejection
            .body_text()
            .contains("unsupported plan step action")
        {
            ApiError::Unsupported
        } else {
            ApiError::InvalidRequest("invalid JSON body")
        }
    })
}

fn validate_hex_hash(value: &str, field: &'static str) -> Result<(), ApiError> {
    if value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        Ok(())
    } else {
        Err(ApiError::InvalidRequest(field))
    }
}

fn validate_request_hash_header(
    headers: &HeaderMap,
    body_request_hash: &str,
) -> Result<(), ApiError> {
    if headers.get_all("x-request-hash").iter().count() > 1 {
        return Err(ApiError::InvalidRequest("request hash header is invalid"));
    }
    let header_hash = headers
        .get("x-request-hash")
        .ok_or(ApiError::InvalidRequest("request hash header is required"))?;
    let header_hash = header_hash
        .to_str()
        .map_err(|_| ApiError::InvalidRequest("request hash header is invalid"))?;
    validate_hex_hash(header_hash, "request hash header")?;
    if header_hash != body_request_hash {
        return Err(ApiError::Conflict);
    }
    Ok(())
}

fn parse_session_version(value: &str) -> Result<u64, ApiError> {
    let value = value.trim();
    if value.len() < 3
        || !value.starts_with('"')
        || !value.ends_with('"')
        || value[1..value.len() - 1].contains('"')
        || value.contains(',')
    {
        return Err(ApiError::InvalidRequest("session version token is invalid"));
    }
    let version = value[1..value.len() - 1]
        .parse::<u64>()
        .map_err(|_| ApiError::InvalidRequest("session version token is invalid"))?;
    if version == 0 {
        return Err(ApiError::InvalidRequest("session version token is invalid"));
    }
    Ok(version)
}

fn parse_staged_classification(value: &str) -> Result<crate::dto::FileClassification, ApiError> {
    match value.trim() {
        "managed" => Ok(crate::dto::FileClassification::Managed),
        "mutable_config" => Ok(crate::dto::FileClassification::MutableConfig),
        "artifact" => Ok(crate::dto::FileClassification::Artifact),
        "generated" => Ok(crate::dto::FileClassification::Generated),
        _ => Err(ApiError::InvalidRequest("x-kitsunebi-classification")),
    }
}

fn required_header<'a>(
    headers: &'a HeaderMap,
    name: &str,
    max: usize,
) -> Result<&'a str, ApiError> {
    if headers.get_all(name).iter().count() != 1 {
        return Err(ApiError::InvalidRequest(
            "required mutation header is invalid",
        ));
    }
    let value = headers
        .get(name)
        .and_then(|v| v.to_str().ok())
        .filter(|v| {
            !v.trim().is_empty()
                && v.len() <= max
                && v.chars().all(|c| !c.is_control())
                && (!name.eq_ignore_ascii_case("if-match") || (v.trim() != "*" && !v.contains(',')))
        })
        .ok_or(ApiError::InvalidRequest(
            "required mutation header is invalid",
        ))?;
    Ok(value)
}
fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}
