[package]
name = "kitsunebi-controller"
description = "Kitsunebi HTTP controller"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
local-auth = ["kitsunebi-api/local-auth"]

[dependencies]
kitsunebi-api.workspace = true
kitsunebi-application.workspace = true
kitsunebi-domain.workspace = true
kitsunebi-storage.workspace = true
kitsunebi-gameap.workspace = true
kitsunebi-tcpshield.workspace = true
kitsunebi-artifacts.workspace = true
kitsunebi-backup.workspace = true
kitsunebi-monitoring = { path = "../kitsunebi-monitoring" }
async-trait = "0.1"
axum = { version = "0.8", features = ["json"] }
futures-util = "0.3"
sqlx = { version = "0.8", default-features = false, features = ["mysql", "runtime-tokio", "tls-rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "net", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = { version = "1", features = ["v4"] }

[lints]
workspace = true
